# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases/demo_testcase_request.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseDemoTestcaseRequest(HttpRunner):

    config = (
        Config("request methods testcase with functions")
        .variables(
            **{
                "foo1": "config_bar1",
                "foo2": "config_bar2",
                "expect_foo1": "config_bar1",
                "expect_foo2": "config_bar2",
            }
        )
        .base_url("https://postman-echo.com")
        .verify(False)
        .export(*["foo3"])
    )

    teststeps = [
        Step(
            RunRequest("get with params")
            .with_variables(
                **{"foo1": "bar11", "foo2": "bar21", "sum_v": "${sum_two(1, 2)}"}
            )
            .get("/get")
            .with_params(**{"foo1": "$foo1", "foo2": "$foo2", "sum_v": "$sum_v"})
            .extract()
            .with_jmespath("body.args.foo2", "foo3")
        ),
    ]


if __name__ == "__main__":
    TestCaseDemoTestcaseRequest().test_start()
